services:
  - type: web
    name: enquiry-backend
    runtime: node
    plan: free
    buildCommand: "cd src/server && npm install"    # <- FIXED
    startCommand: "cd src/server && node index.js"  # <- FIXED
    envVars:
      - key: DBURL
        value: your_mongodb_connection_string_here
